# Generated by Django 5.1.2 on 2024-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_profile_picture_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
